# mkfile script with dependency rules for:
# 1. To count output files from fetched sequences
# 2. To give the total counts data.
## For more information about mk dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

#For running this mkfile, type mk global_report.csv

## Define shell command line which will be used to run scripts.

MKSHELL="/bin/bash"

#mk-global-reporter

#Merge files and table header

global_report.csv:Q: %.tmp
	cat *.tmp >> global_report.csv
	sed -i '1i output_type, num' global_report.csv && rm *.tmp

#Count files by name termination

%.tmp:Q: 
	echo "Counting files"
	echo "fasta, $(ls *.fasta | wc -l)" > global_num_fasta.tmp  #busca cuantas hay para cada tipo de output
        echo "prot_faa, $(ls *-prot.faa | wc -l)" > global_num_protfaa.tmp
        echo "prot_fna, $(ls *-prot.fna | wc -l)" > global_num_protfna.tmp
        echo "prot_faa_error, $(ls *-prot.faa.fetcherror | wc -l)" > global_num_protfaaerror.tmp
        echo "prot_fna_error, $(ls *-prot.fna.fetcherror | wc -l)" > global_num_protfnaerror.tmp
